### ISSUE TITLE
Are these included on the docker images?

### ISSUE THREAD

**Issue by planetahuevo** [weserv/rpms#1]
Sorry if this is written somewhere but I was not able to find it so far. 
Are these rpms included onthe docker images or this is something extra you use on your setup? 

Thanks

**Comment by kleisauke** [comment]
No, this is mainly internal/testing for now. If you want to test this, you'll need to change the Dockerfile like this:

```diff
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -15,7 +15,7 @@ RUN dnf update -y \
     && crb enable \
     && dnf install -y https://rpms.remirepo.net/enterprise/remi-release-10.rpm \
     && dnf config-manager --set-enabled remi \
-    && dnf install -y --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-10.noarch.rpm \
+    && dnf config-manager --add-repo https://rpms.wsrv.nl/weserv.repo \
     && dnf group install -y --with-optional 'Development Tools' \
     && dnf install -y --setopt=tsflags=nodocs --setopt=install_weak_deps=False \
         vips-devel \
```

Or you could extend the Docker image, by doing:
```Dockerfile
FROM ghcr.io/weserv/images:5.x

RUN dnf config-manager --add-repo https://rpms.wsrv.nl/weserv.repo \
    && dnf update -y
```

See also comment https://github.com/weserv/images/issues/318#issuecomment-962633835, if you want to test the `nginx-mod-weserv` package.

**Comment by planetahuevo** [comment]
Thank you very much for the extended answer. I will give it a go.
